export function validateNamePokemon(name) {
  const nameMappings = {
    "nidoran-f": "nidoran♀",
    "nidoran-m": "nidoran♂",
    "mr-mime": "mr Mime",
    "ho-oh": "ho-Oh",
    "deoxys-normal": "deoxys",
    "wormadam-plant": "wormadam",
    "mime-jr": "mime Jr.",
    "porygon-z": "porygon-Z",
    "giratina-altered": "giratina",
    "shaymin-land": "shaymin",
    "basculin-red-striped": "basculin",
    "darmanitan-standard": "darmanitan",
    "tornadus-incarnate": "tornadus",
    "thundurus-incarnate": "thundurus",
    "landorus-incarnate": "landorus",
    "keldeo-ordinary": "keldeo",
    "meloetta-aria": "meloetta",
    "meowstic-male": "meowstic",
    "aegislash-shield": "aegislash",
    "pumpkaboo-average": "pumpkaboo",
    "gourgeist-average": "gourgeist",
    "zygarde-50": "zygarde",
    "oricorio-baile": "oricorio",
    "lycanroc-midday": "lycanroc",
    "wishiwashi-solo": "wishiwashi",
    "type-null": "codigo Cero",
    "minior-red-meteor": "minior",
    "mimikyu-disguised": "mimikyu",
    "tapu-koko": "tapu Koko",
    "tapu-lele": "tapu Lele",
    "tapu-bulu": "tapu Bulu",
    "tapu-fini": "tapu Fini",
    "toxtricity-amped": "toxtricity",
    "mr-rime": "mr Rime",
    "eiscue-ice": "eiscue",
    "indeedee-male": "indeedee",
    "morpeko-full-belly": "morpeko",
    "urshifu-single-strike": "urshifu",
    "basculegion-male": "basculegion",
    "enamorus-incarnate": "enamorus",
    "great-tusk": "colmilargo",
    "scream-tail": "colagrito",
    "brute-bonnet": "furioseta",
    "flutter-mane": "melentaleteo",
    "slither-wing": "reptalada",
    "sandy-shocks": "pelarena",
    "iron-treads": "ferrodada",
    "iron-bundle": "ferrosaco",
    "iron-hands": "ferropalmas",
    "iron-jugulis": "ferrocuello",
    "iron-moth": "ferropolilla",
    "iron-thorns": "ferropuas",
    "wo-chien": "wo-Chien",
    "chien-pao": "chien-Pao",
    "ting-lu": "ting-Lu",
    "chi-yu": "chi-Yu",
    "roaring-moon": "bramaluna",
    "iron-valiant": "ferropaladin",
    "walking-wake": "ondalagua",
    "iron-leaves": "ferroverdor",
  };

  if (nameMappings[name]) return nameMappings[name];

  return name;
}

export function validateNamePokemonForApi(name) {
  const reversedNameMappings = {
    "nidoran♀": "nidoran-f",
    "nidoran♂": "nidoran-m",
    "mr mime": "mr-mime",
    "ho-Oh": "ho-oh",
    deoxys: "deoxys-normal",
    wormadam: "wormadam-plant",
    "mime jr.": "mime-jr",
    "porygon-Z": "porygon-z",
    giratina: "giratina-altered",
    shaymin: "shaymin-land",
    basculin: "basculin-red-striped",
    darmanitan: "darmanitan-standard",
    tornadus: "tornadus-incarnate",
    thundurus: "thundurus-incarnate",
    landorus: "landorus-incarnate",
    keldeo: "keldeo-ordinary",
    meloetta: "meloetta-aria",
    meowstic: "meowstic-male",
    aegislash: "aegislash-shield",
    pumpkaboo: "pumpkaboo-average",
    gourgeist: "gourgeist-average",
    zygarde: "zygarde-50",
    oricorio: "oricorio-baile",
    lycanroc: "lycanroc-midday",
    wishiwashi: "wishiwashi-solo",
    "codigo cero": "type-null",
    minior: "minior-red-meteor",
    mimikyu: "mimikyu-disguised",
    "tapu koko": "tapu-koko",
    "tapu lele": "tapu-lele",
    "tapu bulu": "tapu-bulu",
    "tapu fini": "tapu-fini",
    toxtricity: "toxtricity-amped",
    "mr rime": "mr-rime",
    eiscue: "eiscue-ice",
    indeedee: "indeedee-male",
    morpeko: "morpeko-full-belly",
    urshifu: "urshifu-single-strike",
    basculegion: "basculegion-male",
    enamorus: "enamorus-incarnate",
    colmilargo: "great-tusk",
    colagrito: "scream-tail",
    furioseta: "brute-bonnet",
    melentaleteo: "flutter-mane",
    reptalada: "slither-wing",
    pelarena: "sandy-shocks",
    ferrodada: "iron-treads",
    ferrosaco: "iron-bundle",
    ferropalmas: "iron-hands",
    ferrocuello: "iron-jugulis",
    ferropolilla: "iron-moth",
    ferropuas: "iron-thorns",
    "wo-Chien": "wo-chien",
    "chien-Pao": "chien-pao",
    "ting-Lu": "ting-lu",
    "chi-Yu": "chi-yu",
    bramaluna: "roaring-moon",
    ferropaladin: "iron-valiant",
    ondalagua: "walking-wake",
    ferroverdor: "iron-leaves",
  };

  if (reversedNameMappings[name]) return reversedNameMappings[name];

  return name;
}
